# ==========================================
# Ubuntu 16.04 PHP 5.6 Dockerfile_short
# ==========================================

#
# Cleaned Dockerfile
# Optimized to only apt-update and clean only once
#

# Import previous building block image apache2
#
FROM pvln/ubuntu16.04-lvl1-apache2:1.0

LABEL version="1.0" \
      maintainer="Pierre Veelen <pierre@pvln.nl>"

# ==========================================
# START OF INSTALLING PHP5
# ==========================================

# Inspiration: https://askubuntu.com/questions/756181/installing-php-5-6-on-xenial-16-04
#

# To prevent error message: "sudo: add-apt-repository: command not found"
#

RUN sudo apt-get update && \
    sudo apt-get -y upgrade && \
    sudo apt-get install -y software-properties-common && \
    sudo add-apt-repository -y ppa:ondrej/php && \

# Install php5.6 and cleanup afterwards
#

# Important to update the packages list before installing since they are removed after the install
RUN sudo apt-get update && \
    sudo apt-get -y upgrade && \
    sudo apt-get install -y \
     libapache2-mod-php5.6 \
	 php5.6 \
	 php-pear \
	 php5.6-xcache \
	 php5.6-mysql \
	 php5.6-curl \
	 php5.6-gd && \
   sudo apt-get clean && \
   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#Update the PHP.ini file, enable <? ?> tags and quieten logging.
#
RUN sed -i "s/short_open_tag = Off/short_open_tag = On/" /etc/php/5.6/apache2/php.ini
RUN sed -i "s/error_reporting = .*$/error_reporting = E_ERROR | E_WARNING | E_PARSE/" /etc/php/5.6/apache2/php.ini

# Enable apache mods for PHP.
#
RUN a2enmod php5.6

# ==========================================
# END OF INSTALLING PHP5
# ==========================================


# ==========================================
# START OF PORTS AND VOLUMES
# ==========================================

# Expose apache2 on port 80 of the container
#
EXPOSE 80

# Mountable datafolder path(s) within the container
#
# A key point to be aware of here is that anything after the VOLUME instruction
# in a Dockerfile will not be able to make changes to that volume
#
VOLUME /var/www/html
VOLUME /var/log/apache2

# ==========================================
# END OF PORTS AND VOLUMES
# ==========================================

# ==========================================
# ENTRYPOINT & CMD
# ==========================================

#
# Inspiration: http://goinbigdata.com/docker-run-vs-cmd-vs-entrypoint/
#
# Prefer ENTRYPOINT to CMD when building executable Docker image and you need a command always to be executed.
# Additionally use CMD if you need to provide extra default arguments that could be overwritten from command line when docker container runs.
# Choose CMD if you need to provide a default command and/or arguments that can be overwritten from command line when docker container runs.
#

# Cancel pre-defined start-up instruction and allow us to use our own.
#
ENTRYPOINT []

ADD ./entrypoint.sh /usr/local/bin/
ENTRYPOINT ["/bin/bash","entrypoint.sh"]

# Don't need any specific arguments to be fed into entrypoint 
CMD []
