# ==========================================
# Ubuntu 16.04 Baseline Dockerfile
# ==========================================

# Import baseline image
#
FROM ubuntu:16.04

LABEL version="1.0" \
      maintainer="Pierre Veelen <pierre@pvln.nl>"

# ==========================================
# START OF INSTALLING UTILITIES AND DEFAULTS
# ==========================================

# First install sudo as it was removed as base-package in Ubuntu 16.04
RUN apt-get clean && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y sudo

# ==========================================
# SET THE LOCALE
# ==========================================
#
# C = POSIX standards-compliant locale,
# C.utf8 = POSIX standards-compliant locale, extended to allow the basic use of UTF-8.
# UTF-8 is required as ASCII leads to some problems
#
# en_US.utf8 = American English UTF-8 locale.
# It "knows" which non-ASCII Unicode characters are upper/lower case pairs, and sorts them together,
# upper case immediately before lower case. It also has default sorting orders defined for various non-Latin alphabets.
#
# Inspiration: http://jaredmarkell.com/docker-and-locales/
#              https://blog.mkowalski.net/2016/05/17/solving-locale-issues-with-docker-containers/
#

# make sure that locales package is available
RUN apt-get install --reinstall -y locales
# uncomment chosen locale to enable it's generation
RUN sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
# generate chosen locale
RUN locale-gen en_US.UTF-8
# set system-wide locale settings
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US
ENV LC_ALL en_US.UTF-8
# verify modified configuration
RUN dpkg-reconfigure --frontend noninteractive locales

# ==========================================
# INSTALLING AND CONFIGURING UTILITIES
# ==========================================

RUN sudo apt-get install -y \
       apt-utils \
       nano \
       ssh \
       net-tools && \
    sudo apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# ==========================================
# CONFIGURE TIMEZONE AND LOCALTIME
# ==========================================
#
# Inspiration: https://www.raspberrypi.org/forums/viewtopic.php?t=4977
#
RUN sudo rm /etc/localtime && \
    sudo ln -s /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime && \
    sudo rm /etc/timezone && \
    echo "Europe/Amsterdam" | sudo tee /etc/timezone 

# ==========================================
# END OF UTILITIES AND DEFAULTS
# ==========================================

# ==========================================
# ENTRYPOINT & CMD
# ==========================================
#
# Inspiration: http://goinbigdata.com/docker-run-vs-cmd-vs-entrypoint/
#
# Prefer ENTRYPOINT to CMD when building executable Docker image and you need a command always to be executed. 
# Additionally use CMD if you need to provide extra default arguments that could be overwritten from command line when docker container runs.
# Choose CMD if you need to provide a default command and/or arguments that can be overwritten from command line when docker container runs.
#

# Cancel any pre-defined start-up instruction and allow us to use our own.
#
ENTRYPOINT []

# Add our own entrypoint script.
#
ADD ./entrypoint.sh /usr/local/bin/
ENTRYPOINT ["/bin/bash","entrypoint.sh"]

# Don't need any specific arguments to be fed into entrypoint 
CMD []
